version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-milkyway
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
