spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: springuser
    password: springpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
